# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlRan < Formula
  desc "A Kubernetes addon for running an ephemeral container with a "mounted" volume."
  homepage "https://github.com/puppetlabs/kubectl-ran"
  version "0.1.3"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/puppetlabs/kubectl-ran/releases/download/v0.1.3/kubectl-ran_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "637f933f24bc4f2db43aec00404c7ccec9d3629856696132cca38892049ab4eb"

      def install
        bin.install "kubectl-ran"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/puppetlabs/kubectl-ran/releases/download/v0.1.3/kubectl-ran_0.1.3_Darwin_arm64.tar.gz"
      sha256 "4678d3d894f23ba8285b388dd2946273b560c90727e883d13a5d8c4512b0cf21"

      def install
        bin.install "kubectl-ran"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/puppetlabs/kubectl-ran/releases/download/v0.1.3/kubectl-ran_0.1.3_Linux_arm64.tar.gz"
      sha256 "dc948a66f3c7e6f0f7192410a9efafb410b1930b8442704bc75b6466811ad00e"

      def install
        bin.install "kubectl-ran"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/puppetlabs/kubectl-ran/releases/download/v0.1.3/kubectl-ran_0.1.3_Linux_x86_64.tar.gz"
      sha256 "4619bfe7dcacab784033e0b8fbabe782b3e7c39e21b77a48453a62c723ffec8a"

      def install
        bin.install "kubectl-ran"
      end
    end
  end
end
