name: Brew install tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  install_casks:
    name: Install ${{ matrix.cask }} cask on ${{ matrix.macos }}
    strategy:
      matrix:
        macos: [ 'macos-13', 'macos-14' ]
        cask: [ 'pe-client-tools', 'pe-client-tools-2019.8', 'pdk', 'puppet-agent', 'puppet-agent-7', 'puppet-agent-8', 'puppet-bolt', 'puppet-bolt@2' ]
    env:
      HOMEBREW_LOGS: ~/homebrew-logs
      HOMEBREW_TEMP: ~/homebrew-temp
      HOMEBREW_NO_AUTO_UPDATE: 1
    runs-on: ${{ matrix.macos }}
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: brew install --cask Casks/${{ matrix.cask }}.rb --force
  install_formulae:
    name: Install ${{ matrix.formula }} formula on ${{ matrix.macos }}
    strategy:
      matrix:
        macos: [ 'macos-14' ]
        formula: [ 'kubectl-ran' ]
    runs-on: ${{ matrix.macos }}
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: brew install Formula/${{ matrix.formula }}.rb
